database:
  - name: pg
    host: 192.168.0.187
    port: 15432
    dbname: ontune
    username: ontune
    password: ontune

kafka:
  host: 192.168.0.187
  port: 9093

apiserver:
  port: 8088
  
demo:
  host_count: 4000
  host_change_count: 500
  bpt_count: 500
  interval: 1